import Head from 'next/head'
import {
  Container,
  Heading,

  Button,

} from '@chakra-ui/react'
import { useRouter } from 'next/router'

export default function Home () {
const router = useRouter()
  return (
    <>
      <Head>
        <title>React Query RnD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>React Query Research & Development</Heading>
          <Button
           colorScheme='teal'
           size='md'
           onClick={() => router.push('/products')}
           mt='3'
           mb='3'
           >Go To Example CRUD</Button>
           <div>
            <p>this project is example how implement react query</p>
           </div>
        </Container>
      </main>
    </>
  )
}
